on: 
  push:
    branches: [master]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --target-dir docs-tmp --no-deps
      - name: push docs
        run: |
          git checkout -B gh-pages
          rm -rf docs
          mv docs-tmp docs
          git config --local user.email "docs-action@github.com"
          git config --local user.name "GitHub Action (docs)"
          git add docs
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -m 'Add docs'
          git push -f origin gh-pages
