on: 
  push:
    branches: [master]
    
jobs:
  vccarsall_help:
    runs-on: windows-latest
    steps:
      - run: |
          "c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" /help
        shell: cmd
